<a href="https://colab.research.google.com/github/zidankhainur2/machine-learning-practice/blob/main/Test_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install scikit-image

In [ ]:
from skimage import io, img_as_float, img_as_ubyte
import numpy as np
import matplotlib.pyplot as plt


image = img_as_float(io.imread("/content/DSC03276.JPG"))

#image2 = io.imread("images/test_image.jpg").astype(np.float)
#avoid using astype as it violates assumptions about dtype range.
#for example float should range from 0 to 1 (or -1 to 1) but if you use
#astype to convert to float, the values do not lie between 0 and 1.
#print(image.shape)
#plt.imshow(img)

print(image)

#print(image2)
#image8byte = img_as_ubyte(image)
#print(image8byte)

#End of Skimage

[[[0.34901961 0.31372549 0.24705882]
  [0.36078431 0.3254902  0.25882353]
  [0.34901961 0.31372549 0.24705882]
  ...
  [0.75686275 0.82745098 0.92156863]
  [0.74509804 0.81568627 0.90980392]
  [0.74901961 0.81960784 0.91372549]]

 [[0.35686275 0.32156863 0.25490196]
  [0.36078431 0.3254902  0.25882353]
  [0.34117647 0.30588235 0.23921569]
  ...
  [0.75294118 0.82352941 0.91764706]
  [0.74509804 0.81568627 0.90980392]
  [0.75294118 0.82352941 0.91764706]]

 [[0.36470588 0.32941176 0.2627451 ]
  [0.35294118 0.31764706 0.25098039]
  [0.3254902  0.29019608 0.22352941]
  ...
  [0.75294118 0.82352941 0.91764706]
  [0.74509804 0.81568627 0.90980392]
  [0.76470588 0.83529412 0.92941176]]

 ...

 [[0.27843137 0.25490196 0.2       ]
  [0.26666667 0.24313725 0.18823529]
  [0.25882353 0.23529412 0.18039216]
  ...
  [0.74901961 0.73333333 0.68627451]
  [0.74509804 0.72941176 0.68235294]
  [0.75294118 0.7372549  0.69019608]]

 [[0.2745098  0.25098039 0.19607843]
  [0.27058824 0.24705882 0.19215686]
